// Mocks generated by Mockito 5.0.16 from annotations
// in telleo/test/application/blocs/home/chats/chats_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:telleo/domain/chats/chats_failures.dart' as _i5;
import 'package:telleo/domain/chats/chats_repository.dart' as _i3;
import 'package:telleo/domain/entities/chat_entity.dart' as _i6;
import 'package:telleo/domain/states/chats_data_state.dart' as _i7;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ChatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatsRepository extends _i1.Mock implements _i3.ChatsRepository {
  MockChatsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ChatsFailure, List<_i6.ChatEntity>>> getChats() =>
      (super.noSuchMethod(Invocation.method(#getChats, []),
              returnValue: Future<
                      _i2.Either<_i5.ChatsFailure, List<_i6.ChatEntity>>>.value(
                  _FakeEither_0<_i5.ChatsFailure, List<_i6.ChatEntity>>()))
          as _i4.Future<_i2.Either<_i5.ChatsFailure, List<_i6.ChatEntity>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ChatsDataState].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatsDataState extends _i1.Mock implements _i7.ChatsDataState {
  MockChatsDataState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.ChatEntity> get value =>
      (super.noSuchMethod(Invocation.getter(#value),
          returnValue: <_i6.ChatEntity>[]) as List<_i6.ChatEntity>);
  @override
  String toString() => super.toString();
  @override
  void update(List<_i6.ChatEntity>? value) =>
      super.noSuchMethod(Invocation.method(#update, [value]),
          returnValueForMissingStub: null);
}
